const MAXIMUM_TITLE_LENGTH = 70;

const MAXIMUM_ADDITIONAL_SERVICES_COUNT = 12;

const MAXIMUM_ADDITIONAL_SERVICES_NAME_LENGTH = 40;

const MAXIMUM_IMAGE_COUNT = 10;

const MAXIMUM_VIDEO_COUNT = 5;

const BASE_URL = `https://api.hantify.ru/`;

const PROXY_URL = "https://cors-anywhere.herokuapp.com/";

const IMG_URL = "https://s3.timeweb.cloud/1847a548-39ca82e7-4c39-4c5a-8e85-38f48671a022/services/tumb/302x402/"
export {
  MAXIMUM_TITLE_LENGTH,
  MAXIMUM_ADDITIONAL_SERVICES_COUNT,
  MAXIMUM_ADDITIONAL_SERVICES_NAME_LENGTH,
  MAXIMUM_IMAGE_COUNT,
  BASE_URL,
  MAXIMUM_VIDEO_COUNT,
  PROXY_URL,
  IMG_URL
}
