export const GoodCards = [
  {
    id: 1,
    title: "Good title 1",
    description: "Good description 1",
    image: "https://picsum.photos/200/300",
    isAvailable: true,
    price: 100,
    isFavorite: true,
    isInCart: false,
    quantity: 1,
    comments: [
      { id: 1, text: "Comment 1" },
      { id: 2, text: "Comment 2" },
      { id: 3, text: "Comment 3" },
    ],
    termsOfDelivery: "10 days",
    category: "category 1",
    rating: 4.5,
    reviews: 10,
    selesQty: 100,
  },
  {
    id: 2,
    title: "Good title 2",
    description: "Good description 1",
    image: "https://picsum.photos/200/300",
    isAvailable: true,
    price: 100,
    isFavorite: true,
    isInCart: false,
    quantity: 1,
    comments: [
      { id: 1, text: "Comment 1" },
      { id: 2, text: "Comment 2" },
      { id: 3, text: "Comment 3" },
    ],
    termsOfDelivery: "10 days",
    category: "category 2",
    rating: 4.5,
    reviews: 10,
    selesQty: 100,
  },
  {
    id: 3,
    title: "Good title 3",
    description: "Good description 1",
    image: "https://picsum.photos/200/300",
    isAvailable: true,
    price: 100,
    isFavorite: true,
    isInCart: false,
    quantity: 1,
    comments: [
      { id: 1, text: "Comment 1" },
      { id: 2, text: "Comment 2" },
      { id: 3, text: "Comment 3" },
    ],
    termsOfDelivery: "10 days",
    category: "category 3",
    rating: 4.5,
    reviews: 10,
    selesQty: 100,
  },
  {
    id: 4,
    title: "Good title 4",
    description: "Good description 1",
    image: "https://picsum.photos/200/300",
    isAvailable: true,
    price: 100,
    isFavorite: true,
    isInCart: false,
    quantity: 1,
    comments: [
      { id: 1, text: "Comment 1" },
      { id: 2, text: "Comment 2" },
      { id: 3, text: "Comment 3" },
    ],
    termsOfDelivery: "10 days",
    category: "category 1",
    rating: 4.5,
    reviews: 10,
    selesQty: 100,
  },
]

export type GoodCards = typeof GoodCards[number]
